one:
  rule: genrule
  cmd: sleep 2; cat who.txt > $(out)
  srcs:
    - :who.txt
  outs:
    - one.txt

two:
  rule: genrule
  cmd: sleep 2; node -e 'console.log(`I am two`)' > $(out)
  outs:
    - two.txt

combined:
  rule: genrule
  cmd: sleep 2; cat one.txt two.txt > combined.txt
  srcs:
    - :one.txt
    - :two
  outs:
    - combined.txt
