one:
  rule: genrule
  cmd: sleep 2; cat who.txt > one.txt
  srcs:
    - :who.txt
  outs:
    - one.txt

two:
  rule: genrule
  cmd: sleep 2; echo I am two > two.txt
  outs:
    - two.txt

combined:
  rule: genrule
  cmd: sleep 2; cat one.txt two.txt > combined.txt
  srcs:
    - :one.txt
    - :two
  outs:
    - combined.txt
